In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

WARNING:tensorflow:From C:\Users\simon\anaconda3\envs\dev\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID column, 'EIN'.
application_df = application_df.drop(columns = ['EIN'])

In [2]:
# Look at NAME counts for binning
counts = application_df['NAME'].value_counts()
counts

NAME
PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: count, Length: 19568, dtype: int64

In [4]:
names_replace = list(counts[counts<5].index)

In [5]:
# Replace in dataframe
for name in names_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

NAME
Other                                                                19803
PARENT BOOSTER USA INC                                                1260
TOPS CLUB INC                                                          765
UNITED STATES BOWLING CONGRESS INC                                     700
WASHINGTON STATE UNIVERSITY                                            492
                                                                     ...
GUILDS OF THE SANTA FE OPERA INC                                         5
FAMILY MOTOR COACH ASSOCIATION                                           5
JAMESTOWN SOCIETY                                                        5
MOST WORSHIPFUL PRINCE HALL GRAND LODGE OF FREE & ACCEPTED MASONS        5
PTA HAWAII CONGRESS                                                      5
Name: count, Length: 403, dtype: int64

In [6]:
counts = application_df['APPLICATION_TYPE'].value_counts()
counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(counts[counts<500].index)
application_types_to_replace

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [9]:
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [10]:
countsbinning = application_df['CLASSIFICATION'].value_counts()
countsclassification = countsbinning[countsbinning>1]
countsclassification

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list (countsbinning[countsbinning<100].index)
classifications_to_replace

['C2800',
 'C7100',
 'C1300',
 'C1280',
 'C1230',
 'C1400',
 'C7200',
 'C2300',
 'C1240',
 'C8000',
 'C7120',
 'C1500',
 'C1800',
 'C6000',
 'C1250',
 'C8200',
 'C1238',
 'C1278',
 'C1235',
 'C1237',
 'C7210',
 'C2400',
 'C1720',
 'C4100',
 'C1257',
 'C1600',
 'C1260',
 'C2710',
 'C0',
 'C3200',
 'C1234',
 'C1246',
 'C1267',
 'C1256',
 'C2190',
 'C4200',
 'C2600',
 'C5200',
 'C1370',
 'C1248',
 'C6100',
 'C1820',
 'C1900',
 'C1236',
 'C3700',
 'C2570',
 'C1580',
 'C1245',
 'C2500',
 'C1570',
 'C1283',
 'C2380',
 'C1732',
 'C1728',
 'C2170',
 'C4120',
 'C8210',
 'C2561',
 'C4500',
 'C2150']

In [12]:
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,EIN,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_ACTS MINISTRY,NAME_ACTS MISSIONS,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,10520599,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,10531628,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,10547893,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,10553066,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,10556103,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [14]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
y

# drop 'IS SUCCESSFUL'
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
X

array([[1.05205990e+07, 1.00000000e+00, 5.00000000e+03, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [1.05316280e+07, 1.00000000e+00, 1.08590000e+05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [1.05478930e+07, 1.00000000e+00, 5.00000000e+03, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [9.96012607e+08, 1.00000000e+00, 5.00000000e+03, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [9.96015768e+08, 1.00000000e+00, 5.00000000e+03, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [9.96086871e+08, 1.00000000e+00, 3.65001790e+07, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [15]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [16]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [17]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=7
hidden_nodes_layer2=14
hidden_nodes_layer3=21
nn = tf.keras.models.Sequential()

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

WARNING:tensorflow:From C:\Users\simon\anaconda3\envs\dev\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 3178

 dense_1 (Dense)             (None, 14)                112

 dense_2 (Dense)             (None, 1)                 15

=================================================================
Total params: 3305 (12.91 KB)
Trainable params: 3305 (12.91 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [18]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

WARNING:tensorflow:From C:\Users\simon\anaconda3\envs\dev\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [19]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
WARNING:tensorflow:From C:\Users\simon\anaconda3\envs\dev\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From C:\Users\simon\anaconda3\envs\dev\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

684/684 [==============================] - 2s 2ms/step - loss: 0.5478 - accuracy: 0.7350 - val_loss: 0.4638 - val_accuracy: 0.7891
Epoch 2/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4556 - accuracy: 0.7860 - val_loss: 0.4392 - val_accuracy: 0.8041
Epoch 3/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4391 - accuracy: 0.7896 - val_loss: 0.4370 - val_accuracy: 0.7981
Epoch 4/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4343 - accuracy: 0.7896 - val_loss: 0.4352 - val_accuracy: 0.8028
Epoch 5/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4307 - accuracy: 0.7922 - val_loss: 0.4355 - val_accuracy: 0.8002
Epoch 6/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4284 - accuracy: 0.7935 - val_loss: 0.4352 - val_accuracy: 0.7979
Epoch 7/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4272 - accuracy: 0.7953 - val_loss: 0.4343 - val_accuracy: 0.7987
Epoch 8/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4252 - accuracy: 0.7943 - val_loss: 0.4351 - val_accuracy: 0.7976
Epoch 9/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4251 - accuracy: 0.7955 - val_loss: 0.4362 - val_accuracy: 0.7999
Epoch 10/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4242 - accuracy: 0.7959 - val_loss: 0.4364 - val_accuracy: 0.8002
Epoch 11/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4230 - accuracy: 0.7955 - val_loss: 0.4358 - val_accuracy: 0.7997
Epoch 12/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4216 - accuracy: 0.7962 - val_loss: 0.4351 - val_accuracy: 0.8015
Epoch 13/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4213 - accuracy: 0.7972 - val_loss: 0.4353 - val_accuracy: 0.8020
Epoch 14/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4204 - accuracy: 0.7969 - val_loss: 0.4354 - val_accuracy: 0.7955
Epoch 15/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4204 - accuracy: 0.7961 - val_loss: 0.4375 - val_accuracy: 0.7966
Epoch 16/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4200 - accuracy: 0.7983 - val_loss: 0.4384 - val_accuracy: 0.8010
Epoch 17/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4199 - accuracy: 0.7971 - val_loss: 0.4367 - val_accuracy: 0.8036
Epoch 18/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4194 - accuracy: 0.7975 - val_loss: 0.4370 - val_accuracy: 0.8002
Epoch 19/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4189 - accuracy: 0.7992 - val_loss: 0.4379 - val_accuracy: 0.7992
Epoch 20/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4184 - accuracy: 0.7989 - val_loss: 0.4377 - val_accuracy: 0.7968
Epoch 21/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4179 - accuracy: 0.7987 - val_loss: 0.4371 - val_accuracy: 0.8005
Epoch 22/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4176 - accuracy: 0.7986 - val_loss: 0.4377 - val_accuracy: 0.8012
Epoch 23/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4171 - accuracy: 0.8004 - val_loss: 0.4412 - val_accuracy: 0.8005
Epoch 24/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4164 - accuracy: 0.8008 - val_loss: 0.4408 - val_accuracy: 0.8020
Epoch 25/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4166 - accuracy: 0.8012 - val_loss: 0.4433 - val_accuracy: 0.8012
Epoch 26/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4162 - accuracy: 0.8028 - val_loss: 0.4411 - val_accuracy: 0.8018
Epoch 27/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4154 - accuracy: 0.8015 - val_loss: 0.4408 - val_accuracy: 0.8018
Epoch 28/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4149 - accuracy: 0.8029 - val_loss: 0.4436 - val_accuracy: 0.8007
Epoch 29/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4152 - accuracy: 0.8015 - val_loss: 0.4395 - val_accuracy: 0.8044
Epoch 30/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4148 - accuracy: 0.8031 - val_loss: 0.4386 - val_accuracy: 0.8012
Epoch 31/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4143 - accuracy: 0.8024 - val_loss: 0.4383 - val_accuracy: 0.8051
Epoch 32/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4144 - accuracy: 0.8030 - val_loss: 0.4398 - val_accuracy: 0.8028
Epoch 33/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4141 - accuracy: 0.8027 - val_loss: 0.4393 - val_accuracy: 0.8018
Epoch 34/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4139 - accuracy: 0.8031 - val_loss: 0.4412 - val_accuracy: 0.7999
Epoch 35/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4134 - accuracy: 0.8039 - val_loss: 0.4399 - val_accuracy: 0.8015
Epoch 36/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4138 - accuracy: 0.8042 - val_loss: 0.4383 - val_accuracy: 0.8028
Epoch 37/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4134 - accuracy: 0.8045 - val_loss: 0.4401 - val_accuracy: 0.8025
Epoch 38/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4127 - accuracy: 0.8043 - val_loss: 0.4397 - val_accuracy: 0.8031
Epoch 39/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4129 - accuracy: 0.8032 - val_loss: 0.4389 - val_accuracy: 0.8041
Epoch 40/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4120 - accuracy: 0.8048 - val_loss: 0.4398 - val_accuracy: 0.8041
Epoch 41/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4122 - accuracy: 0.8046 - val_loss: 0.4379 - val_accuracy: 0.8015
Epoch 42/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4118 - accuracy: 0.8040 - val_loss: 0.4401 - val_accuracy: 0.8018
Epoch 43/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4117 - accuracy: 0.8026 - val_loss: 0.4406 - val_accuracy: 0.8007
Epoch 44/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4120 - accuracy: 0.8048 - val_loss: 0.4405 - val_accuracy: 0.8038
Epoch 45/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4113 - accuracy: 0.8052 - val_loss: 0.4398 - val_accuracy: 0.8012
Epoch 46/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4108 - accuracy: 0.8049 - val_loss: 0.4385 - val_accuracy: 0.8038
Epoch 47/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4105 - accuracy: 0.8052 - val_loss: 0.4411 - val_accuracy: 0.7997
Epoch 48/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4103 - accuracy: 0.8046 - val_loss: 0.4414 - val_accuracy: 0.8015
Epoch 49/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4102 - accuracy: 0.8051 - val_loss: 0.4411 - val_accuracy: 0.8023
Epoch 50/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4097 - accuracy: 0.8059 - val_loss: 0.4441 - val_accuracy: 0.8012
Epoch 51/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4098 - accuracy: 0.8065 - val_loss: 0.4426 - val_accuracy: 0.8044
Epoch 52/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4099 - accuracy: 0.8054 - val_loss: 0.4425 - val_accuracy: 0.7999
Epoch 53/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4091 - accuracy: 0.8048 - val_loss: 0.4401 - val_accuracy: 0.7987
Epoch 54/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4088 - accuracy: 0.8058 - val_loss: 0.4417 - val_accuracy: 0.8056

Epoch 55/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4085 - accuracy: 0.8063 - val_loss: 0.4437 - val_accuracy: 0.8025
Epoch 56/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4080 - accuracy: 0.8055 - val_loss: 0.4441 - val_accuracy: 0.8025
Epoch 57/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4084 - accuracy: 0.8052 - val_loss: 0.4433 - val_accuracy: 0.8015
Epoch 58/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4079 - accuracy: 0.8062 - val_loss: 0.4423 - val_accuracy: 0.8031
Epoch 59/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4078 - accuracy: 0.8056 - val_loss: 0.4414 - val_accuracy: 0.8033
Epoch 60/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4077 - accuracy: 0.8063 - val_loss: 0.4423 - val_accuracy: 0.8018
Epoch 61/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4078 - accuracy: 0.8061 - val_loss: 0.4430 - val_accuracy: 0.8044
Epoch 62/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4075 - accuracy: 0.8066 - val_loss: 0.4452 - val_accuracy: 0.7984
Epoch 63/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4070 - accuracy: 0.8060 - val_loss: 0.4439 - val_accuracy: 0.8023
Epoch 64/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4072 - accuracy: 0.8061 - val_loss: 0.4467 - val_accuracy: 0.8023
Epoch 65/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4074 - accuracy: 0.8057 - val_loss: 0.4443 - val_accuracy: 0.8033
Epoch 66/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4070 - accuracy: 0.8071 - val_loss: 0.4445 - val_accuracy: 0.8033
Epoch 67/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4066 - accuracy: 0.8068 - val_loss: 0.4444 - val_accuracy: 0.8025
Epoch 68/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4066 - accuracy: 0.8061 - val_loss: 0.4434 - val_accuracy: 0.8025
Epoch 69/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4065 - accuracy: 0.8075 - val_loss: 0.4435 - val_accuracy: 0.7997
Epoch 70/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4066 - accuracy: 0.8070 - val_loss: 0.4482 - val_accuracy: 0.8033
Epoch 71/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4063 - accuracy: 0.8069 - val_loss: 0.4439 - val_accuracy: 0.8044
Epoch 72/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4062 - accuracy: 0.8070 - val_loss: 0.4437 - val_accuracy: 0.8007
Epoch 73/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4059 - accuracy: 0.8072 - val_loss: 0.4471 - val_accuracy: 0.8015
Epoch 74/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4058 - accuracy: 0.8080 - val_loss: 0.4460 - val_accuracy: 0.8020
Epoch 75/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4058 - accuracy: 0.8075 - val_loss: 0.4468 - val_accuracy: 0.8033
Epoch 76/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4055 - accuracy: 0.8078 - val_loss: 0.4470 - val_accuracy: 0.8025
Epoch 77/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4056 - accuracy: 0.8079 - val_loss: 0.4459 - val_accuracy: 0.7994
Epoch 78/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4053 - accuracy: 0.8060 - val_loss: 0.4489 - val_accuracy: 0.8041
Epoch 79/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4057 - accuracy: 0.8074 - val_loss: 0.4506 - val_accuracy: 0.8018
Epoch 80/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4055 - accuracy: 0.8069 - val_loss: 0.4482 - val_accuracy: 0.8025
Epoch 81/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4053 - accuracy: 0.8071 - val_loss: 0.4500 - val_accuracy: 0.8010
Epoch 82/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4053 - accuracy: 0.8071 - val_loss: 0.4463 - val_accuracy: 0.8012
Epoch 83/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4052 - accuracy: 0.8063 - val_loss: 0.4505 - val_accuracy: 0.7997
Epoch 84/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4048 - accuracy: 0.8071 - val_loss: 0.4456 - val_accuracy: 0.8028
Epoch 85/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4048 - accuracy: 0.8070 - val_loss: 0.4462 - val_accuracy: 0.8018
Epoch 86/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4051 - accuracy: 0.8064 - val_loss: 0.4484 - val_accuracy: 0.8023
Epoch 87/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4049 - accuracy: 0.8067 - val_loss: 0.4465 - val_accuracy: 0.8012
Epoch 88/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4050 - accuracy: 0.8074 - val_loss: 0.4515 - val_accuracy: 0.8015
Epoch 89/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4049 - accuracy: 0.8074 - val_loss: 0.4492 - val_accuracy: 0.8007
Epoch 90/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4044 - accuracy: 0.8076 - val_loss: 0.4506 - val_accuracy: 0.7999
Epoch 91/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4045 - accuracy: 0.8080 - val_loss: 0.4487 - val_accuracy: 0.7984
Epoch 92/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4045 - accuracy: 0.8067 - val_loss: 0.4527 - val_accuracy: 0.7979
Epoch 93/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4043 - accuracy: 0.8079 - val_loss: 0.4528 - val_accuracy: 0.7989
Epoch 94/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4039 - accuracy: 0.8084 - val_loss: 0.4506 - val_accuracy: 0.8002
Epoch 95/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4039 - accuracy: 0.8073 - val_loss: 0.4574 - val_accuracy: 0.7984
Epoch 96/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4041 - accuracy: 0.8075 - val_loss: 0.4522 - val_accuracy: 0.7997
Epoch 97/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4038 - accuracy: 0.8080 - val_loss: 0.4546 - val_accuracy: 0.7992
Epoch 98/100
684/684 [==============================] - 1s 2ms/step - loss: 0.4037 - accuracy: 0.8082 - val_loss: 0.4529 - val_accuracy: 0.8020
Epoch 99/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4042 - accuracy: 0.8081 - val_loss: 0.4532 - val_accuracy: 0.8031
Epoch 100/100
684/684 [==============================] - 1s 1ms/step - loss: 0.4040 - accuracy: 0.8080 - val_loss: 0.4520 - val_accuracy: 0.8007

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.4688 - accuracy: 0.7879 - 266ms/epoch - 994us/step
Loss: 0.4688348174095154, Accuracy: 0.7878717184066772

In [21]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")

C:\Users\simon\anaconda3\envs\dev\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(